Add InsightVM integration
JupiterOne/graph-rapid7 pull request #1
Opened 2020-09-29 13:50 UTC by eXtremeX

Hi everyone :wave: 

This PR includes [Rapid7's InsightVM](https://www.rapid7.com/products/insightvm/) integration - the entities and relationships that seemed high value/of interest for JupiterOne.

Some links that could be useful to anyone trying to familiarize with InsightVM a bit more:
1. [InsightVM's Overview](https://www.rapid7.com/products/insightvm/)
2. [InsightVM's API Reference](https://help.rapid7.com/insightvm/en-us/api/index.html)

We have already started a conversation about what entities/relationships seem to be most impactful and how to ingest them in this [Google Document](https://docs.google.com/document/d/1BbbNtTJvv9TXUT73TpomD4qxrp8fZyG5ziYL8VYoebo/edit?usp=sharing) - @ndowmon gave us great answers and this PR is more or less a direct answer to all of them.

Some notes / useful information:
1. There was a question if we can create a read-only user that has (read-only) access to everything and if we can use its credentials instead of admin's to ingest/iterate through everything. Creating a read-only user is indeed possible (you can toggle some checkboxes to give read access to some resources, such as assets, sites, etc), but in the end, the integration as a whole didn't work when using such user's credentials. The problem was when integration tried to iterate over the users -- it seems that this operation is only given to the role "Global Administrator" which automatically gives permission to everything once selected. It is worth experimenting with this a bit more however, there might be a way but at least it's not that obvious if at all possible. (This is also mentioned in the docs part of the integration).
2. We've modified package.json (temporary, so that we can get to this PR :)) with "NODE_TLS_REJECT_UNAUTHORIZED=0" flag in the "start" and "test" scripts. As it turns out, node-fetch (the request library that we use) rejects unauthorized by default (this is one way to toggle that), and there are some problems when ran without it - every request for localhost:3780 fails with _"reason: self signed certificate"_. This made it work in the development environment since the API we're fetching from (InsightVM API) has self-signed certificates. Any ideas about what should we do here?
3. The only other thing we can point out/ask for is if someone can go through our Asset and Vulnerability step functions and take a bit of look at what fields we're assigning.

For example, the Vulnerability entity uses Vulnerability class since it seems to be most 1-to-1 mapping, however, Vulnerability class requires fields such as `category`, `severity`, `blocking`, `open`, `production` and `public`, meanwhile when we ask InsightVM API to retrieve to us all of the found Vulnerabilities, it only sends us a tiny bit of data per Vulnerability - not enough to construct those fields with meaningful values. For example, we just receive `id`, `instances`, `since`, and `status`. We've been looking around if perhaps we can use more of the API endpoints to ultimately get to all of those necessary details, but it doesn't seem obvious. At the same time, we want to ask what's your stance on situations like these - how worthless are entities if they don't supply all of the required fields? Have you had such situations in the past with other integrations? (The situation is similar with Asset entity).

Kindly let us know if and what needs to be changed (from the notes above and of course anything else that you may spot throughout the code).

Pinging @aiwilliams, @ndowmon, @austinkelleher, @erichs
(We're probably pinging too many people unnecessary, should we just tag you @ndowmon for now? :slightly_smiling_face:)

The current state of graph:
![insightvm_graph](https://user-images.githubusercontent.com/8009142/94566282-748b3080-026a-11eb-850a-bfa2397447ec.png)

2020-09-29 14:08 UTC, ndowmon commented on docs/jupiterone.md
> +
Looks like a bunch of Azure stuff snuck in - can you remove?

2020-09-29 14:14 UTC, ndowmon commented on package.json
> +    "test": "NODE_TLS_REJECT_UNAUTHORIZED=0 jest",
This caused a failure in CI tests on the windows machine: https://github.com/JupiterOne/graph-rapid7/pull/1/checks?check_run_id=1182455250

Would the following work? I assume that you only need the `NODE_TLS_REJECT_UNAUTHORIZED` when making actual HTTP calls, and that the recordings will work fine without that flag, but I could be wrong about that.

```suggestion
    "test:local": "NODE_TLS_REJECT_UNAUTHORIZED=0 && yarn test",
    "test": "jest",
```

2020-09-29 16:17 UTC, eXtremeX commented on docs/jupiterone.md
> +
Uh, weird, it's removed now, sorry about it!

2020-09-29 16:19 UTC, eXtremeX commented on package.json
> +    "test": "NODE_TLS_REJECT_UNAUTHORIZED=0 jest",
That did work, good suggestion! :+1:

2020-09-30 20:17 UTC, ndowmon requested changes
@eXtremeX Thanks for the PR! I _love_ all of the explanations, links, and visuals you add to these PRs. It makes everything much easier from my side.

I noticed a couple of typos and one `RelationshipClass` change that should be simple to fix. I also noted two relationships that I think would be great if you could implement, between `insightvm_user` and `insightvm_asset` as well as `insightvm_scan` and `insightvm_asset`. One looks like it's possible to do with the information you have today, and the other may require one more API call. Let me know if you have any questions.

2020-09-30 20:17 UTC, ndowmon commented on src/constants.ts
> +  },
Would you mind changing this to `SITE_HAS_USER`? That's the convention we've used in other integrations such as Google: https://support.jupiterone.io/hc/en-us/articles/360022902533-Google

2020-10-01 14:46 UTC, ndowmon commented
By the way @eXtremeX, feel free to just tag myself and @aiwilliams on future PRs 😄

2020-10-05 16:46 UTC, eXtremeX commented on src/client.ts
> +        endpoint: `https://${this.insightHost}/api/3/users`,
Yep, that's much nicer, thanks for the suggestion! Not sure why we didn't use something like that originally, looks like we overlooked it somehow.

2020-10-05 16:48 UTC, eXtremeX commented on src/client.ts
> +      }
Thanks for going into a bit of detail there! :+1: 

It's changed, yes that should throw only because of user config error, so now the IntegrationProviderAuthenticationError is being thrown if the response status isn't 200.

2020-10-05 16:54 UTC, eXtremeX commented
Hey @ndowmon, all the changes are done! Let us know in case something is required after you're done reviewing it again. :+1: 

> Thanks for the PR! I love all of the explanations, links, and visuals you add to these PRs. It makes everything much easier from my side.

Great, no problem! Glad the format is useful, reviewing these integrations in a single feature-packed PR probably isn't an easy task (at least initially) so any small thing helps was the motto.

> By the way @eXtremeX, feel free to just tag myself and @aiwilliams on future PRs

Understood, good to know! :smile:

2020-10-05 20:14 UTC, ndowmon commented on src/steps/index.test.ts
> +    await fetchAssetUsers(context);
Can you also add `fetchScanAssets` to this test?

2020-10-05 20:30 UTC, ndowmon reviewed
Hi @eXtremeX thanks again. One last request is to add a call to `fetchScanAssets` in `index.test.ts`, everything else looks good to me.

2020-10-05 21:23 UTC, eXtremeX commented
Thanks, @ndowmon, `fetchScanAssets` has been added to the tests!

2020-10-05 21:25 UTC, ndowmon approved these changes

2020-10-06 17:45 UTC, merged